### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by igorir3** [Advik-B/CurseForge-API#1]
Traceback (most recent call last):
  File "C:\Users\kiril\Desktop\MLP\main.py", line 17, in <module>
    minecraft = client.game(432) # 432 is the ID of Minecraft
                ^^^^^^^^^^^^^^^^
  File "C:\Users\kiril\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\curseforge\base.py", line 65, in game
    return CurseGame.from_dict(self.fetch(f"game/{game_id}"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kiril\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\curseforge\classes\cursegame.py", line 23, in from_dict
    id=data.get("id"),
       ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
NativeCommandExitException: Program "python.exe" ended with non-zero exit code: 1.

**Comment by Advik-B** [comment]
Yikes, this is still is beta tho. Will try to get it fixed...

Also make sure to update curseforge with:
```
pip install --upgrade curseforge
```

**Comment by Advik-B** [comment]
Closing due to inactivity and feedback from the issue author
